apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: org-data
spec:
  type: url
  targets:
    - https://github.com/crizstian/IDP-Test/blob/main/harness-services/domain/org/cristian-lab/catalog-info.yaml
    - https://github.com/crizstian/IDP-Test/blob/main/harness-services/domain/project/el-canario-team/catalog-info.yaml