kind: Component
spec:
  type: Service
  lifecycle: dev
  owner: cristian.ramirez@harness.io
  system: marcio_test
apiVersion: backstage.io/v1alpha1
metadata:
  name: marcio
  description: marcio service
  tags: 
    - java
  annotations:
    harness.io/project-url: https://app.harness.io/ng/account/EeRjnXTnS4GrLG5VNNJZUw/home/orgs/sandbox/projects/marcio_test/details
    harness.io/cd-serviceId: marcio
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: crizstian/marcio
