kind: Component
spec:
  type: Service
  lifecycle: dev
  owner: cristian.ramirez@harness.io
  system: brazil-demo
apiVersion: backstage.io/v1alpha1
metadata:
  name: app-123
  description: app-123 service
  tags: 
    - java
  annotations:
    harness.io/project-url: https://app.harness.io/ng/account/EeRjnXTnS4GrLG5VNNJZUw/home/orgs/sandbox/projects/brazildemo/details
    harness.io/cd-serviceId: app123
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: crizstian/app-123
