apiVersion: backstage.io/v1alpha1
kind: System
spec:
  owner: cristian.ramirez@harness.io
  domain: Sandbox
metadata:
  name: demo-qbr-west
  links:
    - url: https://app.harness.io/ng/account/EeRjnXTnS4GrLG5VNNJZUw/home/orgs/sandbox/projects/demoqbrwest/details
      title:  demo-qbr-west
      icon: dashboard
      type: demo-qbr-west
  description: "Documentation: https://harness.atlassian.net/wiki/spaces/SE/pages/21066940575/Banking+Demo"
  tags: []
