apiVersion: backstage.io/v1alpha1
kind: System
spec:
  owner: cristian.ramirez@harness.io
  domain: Sandbox
metadata:
  name: new-demo-project
  links:
    - url: https://app.harness.io/ng/account/EeRjnXTnS4GrLG5VNNJZUw/home/orgs/sandbox/projects/newdemoproject/details
      title:  new-demo-project
      icon: dashboard
      type: new-demo-project
  description: "Documentation: https://harness.atlassian.net/wiki/spaces/SE/pages/21066940575/Banking+Demo"
  tags: []
