kind: Component
spec:
  type: Service
  lifecycle: dev
  owner: cristian.ramirez@harness.io
  system: rimac-demo
apiVersion: backstage.io/v1alpha1
metadata:
  name: rimac-service-1
  description: rimac-service-1 service
  tags: 
    - java
  annotations:
    harness.io/project-url: https://app.harness.io/ng/account/EeRjnXTnS4GrLG5VNNJZUw/home/orgs/sandbox/projects/rimacdemo/details
    harness.io/cd-serviceId: rimacservice1
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: crizstian/rimac-service-1
